# Generated by Django 4.1.4 on 2023-05-06 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_course_studentscourse_lecture_courselinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='courselinks',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='lectures', to='core.course'),
        ),
    ]
