# Generated by Django 4.1.4 on 2023-05-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_course_active_alter_courselinks_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courselinks',
            old_name='link',
            new_name='access_code',
        ),
        migrations.AddField(
            model_name='course',
            name='full_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='full_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
