# Generated by Django 4.1.4 on 2023-05-08 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_courselinks_use_access_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentscourse',
            name='link',
        ),
    ]
