# Generated by Django 4.1.4 on 2023-05-08 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_studentscourse_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentscourse',
            name='join_link',
            field=models.ForeignKey(default='853fad30-a917-42bf-8903-e27fad242a15', on_delete=django.db.models.deletion.RESTRICT, to='core.courselinks'),
            preserve_default=False,
        ),
    ]
