# Generated by Django 4.1.4 on 2023-05-13 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_fileinfo_description_lecture_files_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homeworks',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('files', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.fileinfo')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.lecture')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
